version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Only allow updates to the patch version
    versioning-strategy: increase-if-necessary
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - '*'
    # Labels to add to pull requests
    labels:
      - 'dependencies'
      - 'github-actions'
    # Auto-merge minor and patch updates that pass CI
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
      include: 'scope'
    # Reviewers for major version updates
    reviewers:
      - 'nivecher' # Replace with your GitHub username
    # Assignees for all updates
    assignees:
      - 'nivecher' # Replace with your GitHub username

  # Maintain Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase-if-necessary
    labels:
      - 'dependencies'
      - 'python'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
      include: 'scope'
    reviewers:
      - 'nivecher' # Replace with your GitHub username
    assignees:
      - 'nivecher' # Replace with your GitHub username
