# ============================================
# Simplified Docker Compose Configuration
# ============================================

services:
  # Development web server
  web:
    image: meal-expense-tracker:dev
    ports:
      - '8000:5000'
    volumes:
      - .:/app
      - app_instance:/app/instance
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg2://mealuser:mealpassword@db:5432/meal_expenses
      - DB_ENGINE=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=mealuser
      - DB_PASSWORD=mealpassword
      - DB_NAME=meal_expenses
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # PostgreSQL database
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=mealuser
      - POSTGRES_PASSWORD=mealpassword
      - POSTGRES_DB=meal_expenses
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U mealuser -d meal_expenses']
      interval: 5s
      timeout: 5s
      retries: 5

  # Database admin interface (optional)
  adminer:
    image: adminer:latest
    ports:
      - '8081:8080'
    depends_on:
      - db

volumes:
  postgres_data:
  app_instance:
