AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to interact with ECR and other AWS services'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
  RepositoryName:
    Type: String
    Description: GitHub repository name

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonECRFullAccess
        - arn:aws:iam::aws:policy/AmazonLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayFullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonSecretsManagerFullAccess
      Policies:
        - PolicyName: GitHubActionsDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # IAM permissions for task execution role
                  - iam:PassRole
                  # DynamoDB permissions for Terraform state locking
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:DescribeTable
                  # S3 permissions for Terraform backend
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetBucketLocation
                  - s3:Describe*
                  - s3:Get*
                  - s3:Tag*
                  # EC2 permissions for VPC setup
                  - ec2:CreateVpc
                  - ec2:CreateSubnet
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:CreateVpcEndpoint
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:Describe*
                  - ec2:Get*
                  # KMS permissions
                  - kms:CreateKey
                  - kms:DescribeKey
                  - kms:EnableKeyRotation
                  - kms:ListAliases
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  # ACM permissions
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:DeleteCertificate
                  - acm:ListCertificates
                  - acm:GetCertificate
                  - acm:ImportCertificate
                  - acm:DeleteCertificateAuthority
                Resource: '*'

Outputs:sour
  RoleARN:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn