---
# CloudFormation Template
# This file uses CloudFormation intrinsic functions (!Sub, !Ref, !If, !GetAtt, etc.)
# which are valid CloudFormation syntax but may trigger YAML linter warnings.
# The template is validated using: aws cloudformation validate-template
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to interact with ECR and other AWS services'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
    Default: nivecher
  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: meal-expense-tracker
  SSORoleArn:
    Type: String
    Description: ARN pattern for SSO role that can assume this role (e.g., arn:aws:sts::${AWS::AccountId}:assumed-role/AWSReservedSSO_AdministratorAccess_*/*)
    Default: ''

Conditions:
  HasSSORole:
    Fn::Not:
      - Fn::Equals:
          - Ref: SSORoleArn
          - ''

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  Fn::Sub: 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
          - Fn::If:
              - HasSSORole
              - Effect: Allow
                Principal:
                  AWS:
                    Ref: SSORoleArn
                Action: sts:AssumeRole
              - Ref: 'AWS::NoValue'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: GitHubActionsDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # IAM permissions for task execution role and policy management
                  - iam:PassRole
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:ListPolicyVersions
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:SetDefaultPolicyVersion
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListAttachedRolePolicies
                  # EC2 permissions for VPC setup
                  - ec2:CreateVpc
                  - ec2:CreateSubnet
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:CreateVpcEndpoint
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:Describe*
                  - ec2:Get*
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - kms:CreateKey
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:Describe*
                  - kms:EnableKeyRotation
                  - kms:Get*
                  - kms:List*
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  - kms:TagResource
                  - kms:UntagResource
                  # SSM Parameter Store permissions
                  - ssm:PutParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:DeleteParameter
                  - ssm:DeleteParameters
                  - ssm:DescribeParameters
                  - ssm:AddTagsToResource
                  - ssm:RemoveTagsFromResource
                  - ssm:ListTagsForResource
                  - sns:GetTopicAttributes
                  - sns:GetSubscriptionAttributes
                  - sns:ListTagsForResource
                  - sns:ListTopics
                  - sns:Publish
                  - sns:SetTopicAttributes
                  - sns:DeleteTopic
                  - route53:ListHostedZones
                  - route53:GetHostedZone
                  - route53:ListResourceRecordSets
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:ListTagsForResource
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:ListTagsForResource
                  # CloudWatch Dashboard permissions
                  - cloudwatch:GetDashboard
                  - cloudwatch:PutDashboard
                  - cloudwatch:DeleteDashboard
                  - cloudwatch:ListDashboards
                  # CloudWatch Metric Alarm permissions
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DescribeAlarmHistory
                  - cloudwatch:SetAlarmState
                  - cloudwatch:ListTagsForResource
                  - cloudwatch:TagResource
                  - cloudwatch:UntagResource
                  # API Gateway v2 permissions
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:DELETE
                  - apigateway:PATCH
                  # ACM permissions
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificateAuthority
                  - acm:Describe*
                  - acm:Get*
                  - acm:ImportCertificate
                  - acm:List*
                  # CloudFront permissions
                  - cloudfront:CreateDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetInvalidation
                  - cloudfront:ListInvalidations
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:ListDistributions
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:ListTagsForResource
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  # CloudFront Response Headers Policy permissions
                  - cloudfront:GetResponseHeadersPolicy
                  - cloudfront:ListResponseHeadersPolicies
                  - cloudfront:CreateResponseHeadersPolicy
                  - cloudfront:UpdateResponseHeadersPolicy
                  - cloudfront:DeleteResponseHeadersPolicy
                  # WAFv2 permissions (required for CloudFront WAF management)
                  - wafv2:GetWebACL
                  - wafv2:ListWebACLs
                  - wafv2:CreateWebACL
                  - wafv2:UpdateWebACL
                  - wafv2:DeleteWebACL
                  - wafv2:GetLoggingConfiguration
                  - wafv2:PutLoggingConfiguration
                  - wafv2:DeleteLoggingConfiguration
                  - wafv2:ListResourcesForWebACL
                  - wafv2:ListTagsForResource
                  - wafv2:TagResource
                  - wafv2:UntagResource
                  - wafv2:AssociateWebACL
                  - wafv2:DisassociateWebACL
                  - wafv2:CreateWebACL
                  - wafv2:UpdateWebACL
                  - wafv2:DeleteWebACL
                  # S3 permissions
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetBucketLocation
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetLifecycleConfiguration
                  - s3:PutLifecycleConfiguration
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketVersioning
                  - s3:PutBucketLogging
                  - s3:GetBucketLogging
                  - s3:PutBucketCORS
                  - s3:GetBucketCORS
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                  # Lambda permissions
                  - lambda:CreatePermission
                  - lambda:GetPolicy
                  - lambda:RemovePermission
                Resource: '*'

Outputs:
  RoleARN:
    Description: ARN of the GitHub Actions IAM Role
    Value:
      Fn::GetAtt:
        - GitHubActionsRole
        - Arn
