---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to interact with ECR and other AWS services'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
    Default: nivecher
  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: meal-expense-tracker

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:sts::562427544284:assumed-role/AWSReservedSSO_AdministratorAccess_c93d252d500730e3/mtd37'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: GitHubActionsDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - ec2:CreateVpc
                  - ec2:CreateSubnet
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:CreateVpcEndpoint
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:Describe*
                  - ec2:Get*
                  - kms:CreateKey
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:Describe*
                  - kms:EnableKeyRotation
                  - kms:Get*
                  - kms:List*
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  - ssm:GetParameter
                  - ssm:DescribeParameters
                  - ssm:ListTagsForResource
                  - ssm:GetParameters
                  - sns:GetTopicAttributes
                  - sns:ListTagsForResource
                  - sns:Publish
                  - route53:ListHostedZones
                  - route53:GetHostedZone
                  - route53:ListResourceRecordSets
                  - route53:ListTagsForResource
                  - logs:ListTagsForResource
                  # CloudWatch Dashboard permissions
                  - cloudwatch:GetDashboard
                  - cloudwatch:PutDashboard
                  - cloudwatch:DeleteDashboard
                  - cloudwatch:ListDashboards
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificateAuthority
                  - acm:Describe*
                  - acm:Get*
                  - acm:ImportCertificate
                  - acm:List*
                  # CloudFront permissions
                  - cloudfront:CreateDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:ListDistributions
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:ListTagsForResource
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  # WAFv2 permissions (required for CloudFront WAF management)
                  - wafv2:GetWebACL
                  - wafv2:ListWebACLs
                  - wafv2:CreateWebACL
                  - wafv2:UpdateWebACL
                  - wafv2:DeleteWebACL
                  - wafv2:GetLoggingConfiguration
                  - wafv2:PutLoggingConfiguration
                  - wafv2:DeleteLoggingConfiguration
                  - wafv2:ListResourcesForWebACL
                  - wafv2:ListTagsForResource
                  - wafv2:TagResource
                  - wafv2:UntagResource
                  - wafv2:AssociateWebACL
                  - wafv2:DisassociateWebACL
                  # S3 permissions
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetBucketLocation
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetLifecycleConfiguration
                  - s3:PutLifecycleConfiguration
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketVersioning
                  - s3:PutBucketLogging
                  - s3:GetBucketLogging
                  - s3:PutBucketCORS
                  - s3:GetBucketCORS
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                Resource: '*'

Outputs:
  RoleARN:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
