AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to interact with ECR and other AWS services'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
    Default: nivecher
  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: meal-expense-tracker

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:sts::562427544284:assumed-role/AWSReservedSSO_AdministratorAccess_c93d252d500730e3/mtd37'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: GitHubActionsDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # IAM permissions for task execution role
                  - iam:PassRole
                  # EC2 permissions for VPC setup
                  - ec2:CreateVpc
                  - ec2:CreateSubnet
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:CreateVpcEndpoint
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:Describe*
                  - ec2:Get*
                  # KMS permissions
                  - kms:CreateKey
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:Describe*
                  - kms:EnableKeyRotation
                  - kms:Get*
                  - kms:List*
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  # ACM permissions
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificateAuthority
                  - acm:Describe*
                  - acm:Get*
                  - acm:ImportCertificate
                  - acm:List*
                Resource: '*'

Outputs:
  RoleARN:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
