---
# CloudFormation Template
# This file uses CloudFormation intrinsic functions (!Sub, !Ref, !If, !GetAtt, etc.)
# which are valid CloudFormation syntax but may trigger YAML linter warnings.
# The template is validated using: aws cloudformation validate-template
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for GitHub Actions to interact with AWS services for CI/CD deployment'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
    Default: nivecher
  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: meal-expense-tracker
  SSORoleArn:
    Type: String
    Description: ARN pattern for SSO role that can assume this role (e.g., arn:aws:sts::${AWS::AccountId}:assumed-role/AWSReservedSSO_AdministratorAccess_*/*)
    Default: ''

Conditions:
  HasSSORole:
    Fn::Not:
      - Fn::Equals:
          - Ref: SSORoleArn
          - ''

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  Fn::Sub: 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
          - Fn::If:
              - HasSSORole
              - Effect: Allow
                Principal:
                  AWS:
                    Ref: SSORoleArn
                Action: sts:AssumeRole
              - Ref: 'AWS::NoValue'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: GitHubActionsDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # IAM permissions for Lambda execution roles and policy management
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:UpdateRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:PassRole
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:ListPolicyVersions
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:SetDefaultPolicyVersion
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:ListAttachedRolePolicies
                  # KMS permissions for encryption keys
                  - kms:CreateKey
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:DescribeKey
                  - kms:Describe*
                  - kms:EnableKeyRotation
                  - kms:Get*
                  - kms:PutKeyPolicy
                  - kms:UpdateKeyDescription
                  - kms:List*
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey
                  - kms:GenerateDataKeyWithoutPlaintext
                  - kms:CreateGrant
                  - kms:ListGrants
                  - kms:RevokeGrant
                  - kms:RetireGrant
                  - kms:TagResource
                  - kms:UntagResource
                  # SSM Parameter Store permissions
                  - ssm:PutParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:DeleteParameter
                  - ssm:DeleteParameters
                  - ssm:DescribeParameters
                  - ssm:AddTagsToResource
                  - ssm:RemoveTagsFromResource
                  - ssm:ListTagsForResource
                  # SNS permissions
                  - sns:CreateTopic
                  - sns:GetTopicAttributes
                  - sns:SetTopicAttributes
                  - sns:DeleteTopic
                  - sns:ListTopics
                  - sns:ListTagsForResource
                  - sns:TagResource
                  - sns:UntagResource
                  - sns:Subscribe
                  - sns:Unsubscribe
                  - sns:Publish
                  # Route 53 permissions
                  - route53:ListHostedZones
                  - route53:GetHostedZone
                  - route53:ListHostedZonesByName
                  - route53:ListResourceRecordSets
                  - route53:GetChange
                  - route53:ChangeResourceRecordSets
                  - route53:CreateHostedZone
                  - route53:DeleteHostedZone
                  - route53:UpdateHostedZoneComment
                  - route53:ListTagsForResource
                  - route53:ChangeTagsForResource
                  # CloudWatch Logs permissions
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:PutRetentionPolicy
                  - logs:ListTagsForResource
                  - logs:TagLogGroup
                  # CloudWatch Dashboard permissions
                  - cloudwatch:GetDashboard
                  - cloudwatch:PutDashboard
                  - cloudwatch:DeleteDashboard
                  - cloudwatch:ListDashboards
                  # CloudWatch Metric Alarm permissions
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DescribeAlarmHistory
                  - cloudwatch:SetAlarmState
                  - cloudwatch:ListTagsForResource
                  - cloudwatch:TagResource
                  - cloudwatch:UntagResource
                  # ACM permissions
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - acm:AddTagsToCertificate
                  - acm:DescribeCertificate
                  - acm:GetCertificate
                  - acm:ListCertificates
                  - acm:ListTagsForCertificate
                  # CloudFront permissions
                  - cloudfront:CreateDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetInvalidation
                  - cloudfront:ListInvalidations
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:ListDistributions
                  - cloudfront:ListOriginAccessControls
                  - cloudfront:GetResponseHeadersPolicy
                  - cloudfront:ListResponseHeadersPolicies
                  - cloudfront:CreateResponseHeadersPolicy
                  - cloudfront:UpdateResponseHeadersPolicy
                  - cloudfront:DeleteResponseHeadersPolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:ListCachePolicies
                  - cloudfront:CreateCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:ListTagsForResource
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                  # Lambda permissions (additional to managed policy)
                  - lambda:CreatePermission
                  - lambda:GetPolicy
                  - lambda:RemovePermission
                Resource: '*'

Outputs:
  RoleARN:
    Description: ARN of the GitHub Actions IAM Role
    Value:
      Fn::GetAtt:
        - GitHubActionsRole
        - Arn
