AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Terraform backend resources (S3 bucket, DynamoDB table, and KMS keys)'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (e.g., dev, staging, prod)
    AllowedPattern: '[a-zA-Z0-9-]+'
    ConstraintDescription: Must contain only alphanumeric characters and hyphens

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, 'prod']

Resources:
  # Single KMS Key for all backend resources
  BackendKmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: KMS key for encrypting Terraform backend resources
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow access for Key Administrators
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: 'true'

  BackendKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/meal-expense-tracker-backend-key'
      TargetKeyId: !Ref BackendKmsKey

  # Main S3 Bucket for Terraform State
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "meal-expense-tracker-tfstate-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt BackendKmsKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: KeepAllVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  # Access Logs Bucket for S3 (using the same KMS key)
  # No separate KMS key needed as we're using the main backend key

  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Condition: IsProd
    Properties:
      BucketName: !Sub 'meal-expense-tracker-tfstate-logs-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt BackendKmsKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: KeepAllVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: TerraformStateBucket
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Allow account root user full access (simplified for testing)
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${TerraformStateBucket}'
              - !Sub 'arn:aws:s3:::${TerraformStateBucket}/*'

  TerraformStateLockTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "meal-expense-tracker-tflock"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !GetAtt BackendKmsKey.Arn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  StateBucketName:
    Description: Name of the S3 bucket for Terraform state
    Value: !Ref TerraformStateBucket
    Export:
      Name: !Sub "${AWS::StackName}-StateBucketName"

  StateLockTableName:
    Description: Name of the DynamoDB table for state locking
    Value: !Ref TerraformStateLockTable
    Export:
      Name: !Sub "${AWS::StackName}-StateLockTableName"

  StateBucketArn:
    Description: ARN of the S3 bucket for Terraform state
    Value: !GetAtt TerraformStateBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StateBucketArn"

  BackendKmsKeyArn:
    Description: ARN of the KMS key used for all backend resources
    Value: !GetAtt BackendKmsKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BackendKmsKeyArn"

  AccessLogsBucketName:
    Description: Name of the S3 bucket for access logs (if created)
    Condition: IsProd
    Value: !If [IsProd, !Ref AccessLogsBucket, !Ref 'AWS::NoValue']
    Export:
      Name: !Sub "${AWS::StackName}-AccessLogsBucketName"
