terraform {
  backend "s3" {
    # This will be filled in by the backend configuration
  }
}

# This file is intentionally left minimal. The actual backend configuration
# is generated by the scripts in the backend/ directory and passed to
# terraform init using the -backend-config flag.
