"""Type stub for dynamically generated version module.

This module is auto-generated by setuptools_scm at build time.
The stub file allows mypy to type-check code that imports from this module.
"""

__version__: str
__build_timestamp__: str
