"""Add price_level field and remove business_status from restaurants

Revision ID: 02a1063bdf4f
Revises: 16ad5aff9d00
Create Date: 2025-09-20 08:37:17.113080

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02a1063bdf4f"
down_revision = "16ad5aff9d00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "price_level",
                sa.Integer(),
                nullable=True,
                comment="Price level from Google Places (0=Free, 1=$1-10, 2=$11-30, 3=$31-60, 4=$61+)",
            )
        )
        batch_op.drop_column("business_status")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("business_status", sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column("price_level")

    # ### end Alembic commands ###
