"""Replace category with type in Restaurant model

Revision ID: 1164647658e4
Revises: 71f878028d61
Create Date: 2025-05-31 10:25:16.658306

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1164647658e4"
down_revision = "71f878028d61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("restaurant")]

    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        if "type" not in columns:
            batch_op.add_column(sa.Column("type", sa.String(length=50), nullable=True))
        if "category" in columns:
            batch_op.drop_column("category")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("restaurant")]

    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        if "category" not in columns:
            batch_op.add_column(
                sa.Column("category", sa.VARCHAR(length=50), nullable=True)
            )
        if "type" in columns:
            batch_op.drop_column("type")

    # ### end Alembic commands ###
