"""Add business_status field to restaurants

Revision ID: 16ad5aff9d00
Revises: 8f66d4cde84d
Create Date: 2025-09-20 08:33:44.109352

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16ad5aff9d00"
down_revision = "8f66d4cde84d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "business_status",
                sa.String(length=50),
                nullable=True,
                comment="Business status from Google Places (OPERATIONAL, CLOSED_TEMPORARILY, etc.)",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("business_status")

    # ### end Alembic commands ###
