"""Add order_type and party_size to expense model

Revision ID: 18329b5f6b6c
Revises: b1009dde6b51
Create Date: 2025-09-01 19:05:28.549012

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18329b5f6b6c"
down_revision = "b1009dde6b51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "order_type",
                sa.String(length=50),
                nullable=True,
                comment="Type of order (e.g., dine_in, takeout, delivery)",
            )
        )
        batch_op.add_column(
            sa.Column(
                "party_size",
                sa.Integer(),
                nullable=False,
                server_default="1",
                comment="Number of people in the party (1-50)",
            )
        )
        batch_op.create_index(batch_op.f("ix_expense_order_type"), ["order_type"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_order_type"))
        batch_op.drop_column("party_size")
        batch_op.drop_column("order_type")

    # ### end Alembic commands ###
