"""empty message

Revision ID: 24d15401b757
Revises: b2c3d4e5f6a7
Create Date: 2026-03-07 18:33:03.546982

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "24d15401b757"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires a default when adding NOT NULL to a table with existing rows.
    # Use text('0') for SQLite boolean false (sa.false() can compile incorrectly on SQLite).
    with op.batch_alter_table("merchant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_chain",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
                comment="Whether this merchant represents a chain brand with multiple locations",
            )
        )

    # ### end Alembic commands ###
    # NOTE: For any new public tables, enable RLS and add policies here.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchant", schema=None) as batch_op:
        batch_op.drop_column("is_chain")

    # ### end Alembic commands ###
