"""20250615_001649

Revision ID: 2cf4cf562dc8
Revises:
Create Date: 2025-06-15 00:16:54.251602

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cf4cf562dc8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
