"""Add located_within field to restaurant model

Revision ID: 42985d8e0812
Revises: 56f3bbd3a157
Create Date: 2025-09-21 16:04:49.363779

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42985d8e0812"
down_revision = "56f3bbd3a157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "located_within",
                sa.String(length=100),
                nullable=True,
                comment="Location within (e.g., mall, airport, hotel)",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("located_within")

    # ### end Alembic commands ###
