"""Add user profile fields

Revision ID: 4b8c8c380a37
Revises: google_place_id_unique
Create Date: 2025-08-31 22:10:40.525869

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b8c8c380a37"
down_revision = "google_place_id_unique"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(length=64), nullable=True, comment="User's first name"))
        batch_op.add_column(sa.Column("last_name", sa.String(length=64), nullable=True, comment="User's last name"))
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=128), nullable=True, comment="User's preferred display name")
        )
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True, comment="User's bio or description"))
        batch_op.add_column(
            sa.Column("avatar_url", sa.String(length=255), nullable=True, comment="URL to user's avatar image")
        )
        batch_op.add_column(sa.Column("phone", sa.String(length=20), nullable=True, comment="User's phone number"))
        batch_op.add_column(
            sa.Column("timezone", sa.String(length=50), nullable=True, comment="User's timezone preference")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("timezone")
        batch_op.drop_column("phone")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("bio")
        batch_op.drop_column("display_name")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
