"""Rename address fields to standard address_line_1 and address_line_2

Revision ID: 56f3bbd3a157
Revises: b6a7f132ab23
Create Date: 2025-09-21 13:29:23.978411

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56f3bbd3a157"
down_revision = "b6a7f132ab23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        # Rename columns to preserve data
        batch_op.alter_column("address", new_column_name="address_line_1", comment="Primary street address")
        batch_op.alter_column(
            "address2", new_column_name="address_line_2", comment="Secondary address (apartment/suite/unit)"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        # Rename columns back to original names
        batch_op.alter_column("address_line_1", new_column_name="address")
        batch_op.alter_column("address_line_2", new_column_name="address2")

    # ### end Alembic commands ###
