"""Add unique constraint on restaurant name and city

Revision ID: 70cbf979b916
Revises: 02ed372e58e3
Create Date: 2025-05-31 11:15:16.683296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cbf979b916'
down_revision = '02ed372e58e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_restaurant_name_city', ['name', 'city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint('uix_restaurant_name_city', type_='unique')

    # ### end Alembic commands ###
