"""Add new fields to Restaurant model

Revision ID: 71f878028d61
Revises: 
Create Date: 2025-05-31 10:17:44.097888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f878028d61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('chain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chain', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('phone')
        batch_op.drop_column('website')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('price_range')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
