"""Add google_place_id to restaurant table

Revision ID: 7593aad35c34
Revises: e8227f2f5667
Create Date: 2025-07-19 09:03:57.845894

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7593aad35c34"
down_revision = "e8227f2f5667"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "google_place_id", sa.String(length=255), nullable=True, comment="Google Place ID for the restaurant"
            )
        )
        batch_op.create_index(batch_op.f("ix_restaurant_google_place_id"), ["google_place_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_restaurant_google_place_id"))
        batch_op.drop_column("google_place_id")

    # ### end Alembic commands ###
