"""Add service_level column to restaurant table

Revision ID: 7943db7ca196
Revises: 4b8c8c380a37
Create Date: 2025-09-01 09:00:40.806610

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7943db7ca196"
down_revision = "4b8c8c380a37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service_level",
                sa.String(length=50),
                nullable=True,
                comment="Service level (fine_dining, casual_dining, fast_casual, quick_service)",
            )
        )
        batch_op.create_index(batch_op.f("ix_restaurant_service_level"), ["service_level"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_restaurant_service_level"))
        batch_op.drop_column("service_level")

    # ### end Alembic commands ###
