"""empty message

Revision ID: 8f66d4cde84d
Revises: 18329b5f6b6c
Create Date: 2025-09-01 20:24:08.757302

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f66d4cde84d"
down_revision = "18329b5f6b6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column(
            "party_size", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'1'")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column(
            "party_size", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("'1'")
        )

    # ### end Alembic commands ###
