"""Add domain model extensions: Merchant, Visit, Receipt entities and extend Restaurant/Expense

Revision ID: 9d3e86eb77e6
Revises: c1d4a8f9e2b7
Create Date: 2026-02-21 17:04:33.739760

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9d3e86eb77e6"
down_revision = "c1d4a8f9e2b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("visit_id", sa.Integer(), nullable=True, comment="Optional reference to a visit"))
        batch_op.create_index(batch_op.f("ix_expense_visit_id"), ["visit_id"], unique=False)
        batch_op.create_foreign_key("fk_expense_visit", "visit", ["visit_id"], ["id"], ondelete="SET NULL")

    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("merchant_id", sa.Integer(), nullable=True, comment="Optional reference to the merchant/brand")
        )
        batch_op.create_index(batch_op.f("ix_restaurant_merchant_id"), ["merchant_id"], unique=False)
        batch_op.create_foreign_key("fk_restaurant_merchant", "merchant", ["merchant_id"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###
    # NOTE: For any new public tables, enable RLS and add policies here.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_constraint("fk_restaurant_merchant", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_restaurant_merchant_id"))
        batch_op.drop_column("merchant_id")

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_constraint("fk_expense_visit", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_expense_visit_id"))
        batch_op.drop_column("visit_id")

    # ### end Alembic commands ###
