"""Add color field to Category model

Revision ID: a51305130893
Revises: c7606b428c7b
Create Date: 2025-06-28 22:21:48.426637

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a51305130893"
down_revision = "c7606b428c7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("color", sa.String(length=20), nullable=False, comment="Hex color code for the category")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###
