"""Add api_cache table for simple caching

Revision ID: b3f2afd229ed
Revises: 1a2b3c4d5e67
Create Date: 2025-10-03 16:03:07.958776

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3f2afd229ed"
down_revision = "1a2b3c4d5e67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_cache_key"), ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_cache_key"))

    op.drop_table("api_cache")
    # ### end Alembic commands ###
