"""Add address2 field to Restaurant model

Revision ID: b6a7f132ab23
Revises: ff72ad1a9c25
Create Date: 2025-09-21 13:25:49.401202

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6a7f132ab23"
down_revision = "ff72ad1a9c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("address2", sa.String(length=200), nullable=True, comment="Address line 2 (apartment/suite)")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("address2")

    # ### end Alembic commands ###
