"""Add latitude and longitude fields to restaurants

Revision ID: be3f0f9d0b9a
Revises: 02a1063bdf4f
Create Date: 2025-09-20 08:54:38.261989

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be3f0f9d0b9a"
down_revision = "02a1063bdf4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True, comment="Restaurant latitude coordinate"))
        batch_op.add_column(
            sa.Column("longitude", sa.Float(), nullable=True, comment="Restaurant longitude coordinate")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")

    # ### end Alembic commands ###
