"""Add user_id to restaurant table

Revision ID: c34a69dde699
Revises:
Create Date: 2025-06-28 14:26:31.401607

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c34a69dde699"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f("uix_restaurant_name_city"), type_="unique")
        batch_op.create_index(batch_op.f("ix_restaurant_user_id"), ["user_id"], unique=False)
        batch_op.create_unique_constraint("uix_restaurant_name_city_user", ["name", "city", "user_id"])
        batch_op.create_foreign_key("fk_restaurant_user_id", "user", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_constraint("fk_restaurant_user_id", type_="foreignkey")
        batch_op.drop_constraint("uix_restaurant_name_city_user", type_="unique")
        batch_op.drop_index(batch_op.f("ix_restaurant_user_id"))
        batch_op.create_unique_constraint(batch_op.f("uix_restaurant_name_city"), ["name", "city"])
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
