"""Add Google Places fields to Restaurant model

Revision ID: c7606b428c7b
Revises: c34a69dde699
Create Date: 2025-06-28 22:10:51.422363

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c7606b428c7b"
down_revision = "c34a69dde699"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_place_id", sa.String(length=255), nullable=True, comment="Google Maps Place ID")
        )
        batch_op.add_column(
            sa.Column("place_name", sa.String(length=255), nullable=True, comment="Official name from Google Places")
        )
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True, comment="Geographic latitude"))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True, comment="Geographic longitude"))
        batch_op.create_index(batch_op.f("ix_restaurant_google_place_id"), ["google_place_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_restaurant_google_place_id"))
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")
        batch_op.drop_column("place_name")
        batch_op.drop_column("google_place_id")

    # ### end Alembic commands ###
