"""empty message

Revision ID: d063f6577ecb
Revises: 9b7f3c7b97be
Create Date: 2025-08-30 07:08:31.922562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d063f6577ecb"
down_revision = "9b7f3c7b97be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("latitude")
        batch_op.drop_column("longitude")
        batch_op.drop_column("price_range")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price_range", sa.SMALLINT(), nullable=True))
        batch_op.add_column(sa.Column("longitude", sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column("latitude", sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
