"""Add primary_type field to restaurants table

Revision ID: ff72ad1a9c25
Revises: be3f0f9d0b9a
Create Date: 2025-09-20 09:41:14.426212

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff72ad1a9c25"
down_revision = "be3f0f9d0b9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "primary_type",
                sa.String(length=100),
                nullable=True,
                comment="Primary business type from Google Places API (e.g., restaurant, cafe, bar)",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("restaurant", schema=None) as batch_op:
        batch_op.drop_column("primary_type")

    # ### end Alembic commands ###
