name: Commit Message Validator

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches: [main]

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate commit messages
        run: |
          commitlint --edit
        env:
          COMMITLINT_CONFIG: >
            {
              "extends": ["@commitlint/config-conventional"],
              "rules": {
                "type-enum": [
                  2,
                  "always",
                  [
                    "feat",
                    "fix",
                    "docs",
                    "style",
                    "refactor",
                    "perf",
                    "test",
                    "chore",
                    "ci",
                    "build"
                  ]
                ],
                "subject-case": [
                  2,
                  "never",
                  ["sentence-case", "start-case", "pascal-case", "upper-case"]
                ]
              }
            }
        if: ${{ github.event.pull_request }}

      - name: Get commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }})
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: Extract version from commit message
        id: version
        run: |
          COMMIT_MESSAGE=${{ steps.commit_message.outputs.message }}
          if [[ $COMMIT_MESSAGE =~ (feat|fix) ]]; then
            if [[ $COMMIT_MESSAGE =~ "BREAKING CHANGE" ]]; then
              echo "bump=MAJOR" >> $GITHUB_OUTPUT
            elif [[ $COMMIT_MESSAGE =~ "feat" ]]; then
              echo "bump=MINOR" >> $GITHUB_OUTPUT
            elif [[ $COMMIT_MESSAGE =~ "fix" ]]; then
              echo "bump=PATCH" >> $GITHUB_OUTPUT
            fi
          fi
