name: CI/CD Pipeline

# Global environment variables
env:
  # Application settings
  APP_NAME: meal-expense-tracker
  PYTHON_VERSION: '3.13' # Using 3.13 as specified in pyproject.toml
  PYTHONPATH: ${{ github.workspace }}
  FLASK_APP: wsgi:app
  FLASK_ENV: test
  TESTING: 'true'
  NODE_VERSION: '20'

  # Deployment settings
  ENV: ${{ github.event.inputs.environment || 'dev' }}
  TF_ENV: ${{ github.event.inputs.environment || 'dev' }}
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY || '123456789012.dkr.ecr.us-east-1.amazonaws.com' }}

  # Cache settings
  CACHE_VERSION: v3

# Required permissions for the workflow
permissions:
  contents: read
  id-token: write
  actions: read
  checks: write
  statuses: write
  security-events: write # Required for CodeQL
  packages: read # Required for package caching

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      terraform_apply:
        description: 'Run terraform apply?'
        required: false
        type: boolean
        default: false

jobs:
  # Quality gate - comprehensive testing and linting
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-suite: ['unit', 'integration', 'lint', 'security']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper versioning

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            venv/
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-pip-

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Setup Node.js (for frontend linting)
        if: matrix.test-suite == 'lint'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        if: matrix.test-suite == 'lint'
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then 
              npm ci
            else 
              npm install
            fi
          else
            echo "No package.json found, skipping npm dependencies"
          fi

      - name: Run unit tests
        if: matrix.test-suite == 'unit'
        run: |
          source venv/bin/activate
          make test-unit

      - name: Run integration tests
        if: matrix.test-suite == 'integration'
        run: |
          source venv/bin/activate
          make test-integration

      - name: Run linting and formatting checks
        if: matrix.test-suite == 'lint'
        run: |
          source venv/bin/activate
          make lint

      - name: Run security checks
        if: matrix.test-suite == 'security'
        run: |
          source venv/bin/activate
          make security-check

      - name: Upload coverage reports
        if: matrix.test-suite == 'unit'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  # Enhanced security scanning
  security-scan:
    name: Security Scan
    needs: quality-gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: security-extended,security-and-quality
          tools: latest

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Install security tools
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          pip install semgrep detect-secrets

      - name: Run Semgrep
        run: semgrep --config=p/ci --error-on-findings .

      - name: Run Grype vulnerability scan
        run: |
          GRYPE_DB_AUTO_UPDATE=false /usr/local/bin/grype dir:. --fail-on high

      - name: Detect secrets
        run: |
          detect-secrets scan --update .secrets.baseline
          detect-secrets audit .secrets.baseline --report --fail

  # Version tagging - only after all checks pass
  version-tag:
    name: Version & Tag
    needs: [quality-gate, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install setuptools-scm
        run: |
          python -m pip install --upgrade pip
          pip install setuptools-scm[toml]

      - name: Generate version
        id: version
        run: |
          # Generate version using setuptools-scm (based on git tags)
          VERSION=$(python -m setuptools_scm)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      - name: Create version file
        run: |
          # Generate version file for build
          python -m setuptools_scm
          
      - name: Commit version file
        run: |
          # Commit the generated version file if it changed
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f "app/_version.py" ] && git diff --exit-code app/_version.py; then
            echo "Version file unchanged"
          else
            git add app/_version.py
            git commit -m "chore: update version to ${{ steps.version.outputs.version }} [skip ci]" || echo "No version changes to commit"
          fi

      - name: Create and push tag
        run: |
          # Create annotated tag with version info
          TAG="${{ steps.version.outputs.tag }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
          else
            git tag -a "$TAG" -m "Release ${{ steps.version.outputs.version }}"
            git push origin "$TAG"
            echo "Created and pushed tag: $TAG"
          fi

  build:
    name: Build and Push
    needs: [quality-gate, security-scan, version-tag]
    if: github.event_name != 'pull_request' && needs.version-tag.result == 'success'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/poetry.lock'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ needs.version-tag.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
          labels: |
            org.opencontainers.image.version=${{ needs.version-tag.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    needs: [quality-gate, security-scan, version-tag, build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.event.inputs.environment == 'dev')
    environment: ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Setup Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          sudo unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
          terraform --version

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          make TF_ENV=${{ github.event.inputs.environment }} tf-init
          if [ "${{ github.event.inputs.terraform_apply }}" = "true" ]; then
            make TF_ENV=${{ github.event.inputs.environment }} tf-apply
          fi

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
      #     aws-region: ${{ env.AWS_REGION }}
      #     role-session-name: GitHubActions-Deploy

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ env.ECR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
      #       ${{ env.ECR_REGISTRY }}/${{ env.APP_NAME }}:${{ env.ENV }}-latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     build-args: |
      #       BUILDKIT_INLINE_CACHE=1
      #       ENVIRONMENT=${{ env.ENV }}

      # - name: Deploy to ECS
      #   run: |
      #     ECS_SERVICE="${{ env.APP_NAME }}-${{ env.ENV }}"

      #     # Update the ECS service with the new task definition
      #     aws ecs update-service \
      #       --cluster ${{ env.ENV }}-cluster \
      #       --service $ECS_SERVICE \
      #       --force-new-deployment \
      #       --region ${{ env.AWS_REGION }}

      #     # Wait for the service to stabilize
      #     aws ecs wait services-stable \
      #       --cluster ${{ env.ENV }}-cluster \
      #       --services $ECS_SERVICE \
      #       --region ${{ env.AWS_REGION }}

      # - name: Run Database Migrations
      #   run: |
      #     TASK_DEFINITION=$(aws ecs describe-services \
      #       --cluster ${{ env.ENV }}-cluster \
      #       --services ${{ env.APP_NAME }}-${{ env.ENV }} \
      #       --query 'services[0].taskDefinition' \
      #       --output text \
      #       --region ${{ env.AWS_REGION }})

      #     aws ecs run-task \
      #       --cluster ${{ env.ENV }}-cluster \
      #       --task-definition $TASK_DEFINITION \
      #       --launch-type FARGATE \
      #       --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.SUBNET_IDS }}],securityGroups=[${{ secrets.SECURITY_GROUP_IDS }}],assignPublicIp=ENABLED}" \
      #       --overrides '{"containerOverrides":[{"name":"app","command":["flask","db","upgrade"]}]}'

      - name: Verify Deployment
        run: |
          LOAD_BALANCER_DNS=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.ENV }}-stack \
            --query 'Stacks[0].Outputs[?OutputKey==`LoadBalancerDNS`].OutputValue' \
            --output text \
            --region ${{ env.AWS_REGION }})

          curl --retry 5 --retry-delay 5 --retry-max-time 30 $LOAD_BALANCER_DNS/health

  terraform:
    name: Terraform (${{ github.event.inputs.environment || 'dev' }})
    needs: [quality-gate, security-scan, version-tag]
    if: github.event_name == 'push' || github.event.inputs.terraform_apply == 'true'
    environment: ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.1

      - name: Run TFLint
        run: |
          cd terraform
          tflint --init
          tflint --format=compact --recursive

      - name: Terraform Format
        run: |
          cd terraform
          terraform fmt -check -recursive -diff

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config=environments/${{ env.TF_ENV }}/backend.tfvars \
                        -backend-config="key=${{ env.TF_ENV }}/terraform.tfstate"

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan \
            -var-file=environments/${{ env.TF_ENV }}/variables.tfvars \
            -out=tfplan \
            -input=false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: terraform/tfplan
          if-no-files-found: error

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.ENV == 'dev' || github.event.inputs.terraform_apply == 'true'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

  notify:
    name: Notify
    needs: [deploy, terraform, version-tag]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Set environment status
        id: set_status
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "STATUS=succeeded" >> $GITHUB_OUTPUT
            echo "COLOR=good" >> $GITHUB_OUTPUT
            echo "EMOJI=✅" >> $GITHUB_OUTPUT
          else
            echo "STATUS=failed" >> $GITHUB_OUTPUT
            echo "COLOR=danger" >> $GITHUB_OUTPUT
            echo "EMOJI=❌" >> $GITHUB_OUTPUT
          fi
          echo "ENV=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_OUTPUT

      - name: Send Deployment Status
        uses: actions/github-script@v7
        if: success() || failure()
        env:
          VERSION: ${{ needs.version-tag.outputs.version || 'unknown' }}
          TAG: ${{ needs.version-tag.outputs.tag || 'unknown' }}
        with:
          script: |
            const { STATUS, COLOR, ENV, EMOJI, VERSION, TAG } = process.env;
            const repo = context.repo;
            const workflowRunId = context.runId;
            const workflowUrl = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${workflowRunId}`;

            // Create a comment on the PR if this is a PR
            if (context.eventName === 'pull_request') {
              await github.rest.issues.createComment({
                ...repo,
                issue_number: context.issue.number,
                body: `${EMOJI} **Deployment to ${ENV} ${STATUS}**\n\n` +
                      `- **Version:** ${VERSION}\n` +
                      `- **Tag:** ${TAG}\n` +
                      `- **Workflow:** [View Workflow Run](${workflowUrl})\n` +
                      `- **Commit:** ${context.sha.slice(0, 7)}\n` +
                      `- **Triggered by:** ${context.actor}\n`
              });
            }

            // Update PR check status
            await github.rest.checks.create({
              ...repo,
              name: `Deployment to ${ENV}`,
              head_sha: context.sha,
              status: 'completed',
              conclusion: STATUS === 'succeeded' ? 'success' : 'failure',
              details_url: workflowUrl,
              output: {
                title: `Deployment ${STATUS} - Version ${VERSION}`,
                summary: `Deployment to ${ENV} ${STATUS} - Version ${VERSION}`,
                text: `Workflow run: ${workflowUrl}\nVersion: ${VERSION}\nTag: ${TAG}`
              }
            });
